import type { ProjectData } from "./types";

const DEMO_UPDATED_AT = "2026-05-16T01:30:00.000Z";

export const demoProjectData: ProjectData = {
  project: {
    id: "project-demo-release-readiness",
    name: "Release Readiness Tracker",
    version: "2.4.0",
    updatedAt: DEMO_UPDATED_AT,
  },
  items: [
    {
      id: "ur-rel-1",
      type: "UR",
      index: 1,
      domainIndex: 1,
      customPrefix: "REL",
      name: "Go/No-Go checklist review",
      content:
        "Release managers must review a single checklist that shows scope, unresolved risks, and deployment blockers before approving a production release.",
      reporter: "Program Ops",
      reviewStatus: "stable",
      tags: ["release", "governance"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-qa-1",
      type: "UR",
      index: 2,
      domainIndex: 1,
      customPrefix: "QA",
      name: "Latest verification signal",
      content:
        "Quality leads must confirm the latest automated and manual verification results without switching to external tools.",
      reporter: "QA Lead",
      reviewStatus: "stable",
      tags: ["qa", "visibility"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-risk-1",
      type: "UR",
      index: 3,
      domainIndex: 1,
      customPrefix: "RISK",
      name: "Active dependency risk tracking",
      content:
        "Teams must record release risks, owners, and mitigation status so unresolved cross-team dependencies are visible before launch.",
      reporter: "Delivery Manager",
      reviewStatus: "needs review",
      tags: ["risk", "dependency"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-wf-1",
      type: "SR",
      index: 1,
      domainIndex: 1,
      customPrefix: "WF",
      name: "Release workflow orchestration",
      priority: "R",
      content:
        "The system shall keep a release checklist with explicit states for draft, in review, approved, blocked, and shipped, and shall record state transitions with timestamps.",
      acceptanceCriteria:
        "A release can move to approved only when all required checklist items are complete and no blocker item remains open.",
      reviewStatus: "approved",
      tags: ["workflow", "audit"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-ver-1",
      type: "SR",
      index: 2,
      domainIndex: 1,
      customPrefix: "VER",
      name: "Verification evidence rollup",
      priority: "R",
      content:
        "The system shall aggregate automated test status, manual QA sign-off, and deployment verification into a single readiness summary for each release.",
      acceptanceCriteria:
        "The readiness summary shows the latest source, status, owner, and update time for every verification stream.",
      reviewStatus: "approved",
      tags: ["verification", "summary"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-risk-1",
      type: "SR",
      index: 3,
      domainIndex: 1,
      customPrefix: "RISK",
      name: "Risk register and mitigation tracking",
      priority: "R",
      content:
        "The system shall store active release risks, mitigation plans, owning teams, and due dates, and shall surface blocked items in the review panel.",
      constraints:
        "Each risk item must have one owner and one target resolution date before release approval.",
      reviewStatus: "in review",
      tags: ["risk", "operations"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-api-1",
      type: "FEATURE",
      index: 1,
      domainIndex: 1,
      customPrefix: "API",
      name: "Release snapshot API",
      content:
        "REST endpoint that returns the current checklist state, unresolved blockers, linked risks, and verification summary for a target release.",
      owner: "Platform Team",
      verificationStatus: "passed",
      reviewStatus: "approved",
      tags: ["backend", "api"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-qa-1",
      type: "FEATURE",
      index: 2,
      domainIndex: 1,
      customPrefix: "QA",
      name: "Verification summary panel",
      content:
        "UI panel that merges CI status, manual QA sign-off, and rollout checks into a compact release summary with status chips and timestamps.",
      owner: "Frontend Team",
      verificationStatus: "pending",
      reviewStatus: "approved",
      tags: ["frontend", "qa"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-risk-1",
      type: "FEATURE",
      index: 3,
      domainIndex: 1,
      customPrefix: "RISK",
      name: "Risk escalation alerts",
      content:
        "Notification rule set that flags overdue mitigation items and blocked dependencies to release owners before the approval window closes.",
      owner: "Release Ops",
      verificationStatus: "blocked",
      reviewStatus: "needs review",
      tags: ["alerts", "risk"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
  ],
  links: [
    {
      id: "link-ur-rel-sr-wf",
      sourceId: "ur-rel-1",
      targetId: "sr-wf-1",
      type: "UR_TO_SR",
      createdAt: DEMO_UPDATED_AT,
    },
    {
      id: "link-ur-qa-sr-ver",
      sourceId: "ur-qa-1",
      targetId: "sr-ver-1",
      type: "UR_TO_SR",
      createdAt: DEMO_UPDATED_AT,
    },
    {
      id: "link-ur-risk-sr-risk",
      sourceId: "ur-risk-1",
      targetId: "sr-risk-1",
      type: "UR_TO_SR",
      createdAt: DEMO_UPDATED_AT,
    },
    {
      id: "link-sr-wf-ft-api",
      sourceId: "sr-wf-1",
      targetId: "ft-api-1",
      type: "SR_TO_FEATURE",
      createdAt: DEMO_UPDATED_AT,
    },
    {
      id: "link-sr-ver-ft-qa",
      sourceId: "sr-ver-1",
      targetId: "ft-qa-1",
      type: "SR_TO_FEATURE",
      createdAt: DEMO_UPDATED_AT,
    },
    {
      id: "link-sr-risk-ft-risk",
      sourceId: "sr-risk-1",
      targetId: "ft-risk-1",
      type: "SR_TO_FEATURE",
      createdAt: DEMO_UPDATED_AT,
    },
  ],
};
