import type { ProjectData } from "./types";

const DEMO_UPDATED_AT = "2026-05-16T01:45:00.000Z";

export type DemoLanguage = "en" | "ko";

const sharedLinks: ProjectData["links"] = [
  {
    id: "link-ur-auth-sr-auth",
    sourceId: "ur-auth-1",
    targetId: "sr-auth-1",
    type: "UR_TO_SR",
    createdAt: DEMO_UPDATED_AT,
  },
  {
    id: "link-ur-cart-sr-cart",
    sourceId: "ur-cart-1",
    targetId: "sr-cart-1",
    type: "UR_TO_SR",
    createdAt: DEMO_UPDATED_AT,
  },
  {
    id: "link-ur-pay-sr-pay",
    sourceId: "ur-pay-1",
    targetId: "sr-pay-1",
    type: "UR_TO_SR",
    createdAt: DEMO_UPDATED_AT,
  },
  {
    id: "link-ur-ship-sr-ship",
    sourceId: "ur-ship-1",
    targetId: "sr-ship-1",
    type: "UR_TO_SR",
    createdAt: DEMO_UPDATED_AT,
  },
  {
    id: "link-sr-auth-ft-auth",
    sourceId: "sr-auth-1",
    targetId: "ft-auth-1",
    type: "SR_TO_FEATURE",
    createdAt: DEMO_UPDATED_AT,
  },
  {
    id: "link-sr-cart-ft-cart",
    sourceId: "sr-cart-1",
    targetId: "ft-cart-1",
    type: "SR_TO_FEATURE",
    createdAt: DEMO_UPDATED_AT,
  },
  {
    id: "link-sr-pay-ft-pay",
    sourceId: "sr-pay-1",
    targetId: "ft-pay-1",
    type: "SR_TO_FEATURE",
    createdAt: DEMO_UPDATED_AT,
  },
  {
    id: "link-sr-ship-ft-ship",
    sourceId: "sr-ship-1",
    targetId: "ft-ship-1",
    type: "SR_TO_FEATURE",
    createdAt: DEMO_UPDATED_AT,
  },
];

export const demoProjectDataEn: ProjectData = {
  project: {
    id: "project-demo-commerce-order-flow",
    name: "Commerce Order Flow Demo",
    version: "1.2.0",
    updatedAt: DEMO_UPDATED_AT,
  },
  items: [
    {
      id: "ur-auth-1",
      type: "UR",
      index: 1,
      domainIndex: 1,
      customPrefix: "AUTH",
      name: "Customer sign-in",
      content:
        "Returning customers must be able to sign in with email and password before they access saved profile and order features.",
      reporter: "Growth PM",
      reviewStatus: "stable",
      tags: ["account", "mvp"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-cart-1",
      type: "UR",
      index: 2,
      domainIndex: 1,
      customPrefix: "CART",
      name: "Add products to cart",
      content:
        "Shoppers must be able to add one or more products to a cart, adjust quantity, and keep the latest subtotal visible before checkout.",
      reporter: "Commerce PM",
      reviewStatus: "stable",
      tags: ["cart", "mvp"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-pay-1",
      type: "UR",
      index: 3,
      domainIndex: 1,
      customPrefix: "PAY",
      name: "Complete payment",
      content:
        "Customers must be able to submit payment for the current cart and receive a clear success or failure result without duplicate charges.",
      reporter: "Payments PM",
      reviewStatus: "stable",
      tags: ["payment", "checkout"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-ship-1",
      type: "UR",
      index: 4,
      domainIndex: 1,
      customPrefix: "SHIP",
      name: "Track delivery status",
      content:
        "After placing an order, customers must be able to review the current delivery status and the latest shipment update in one place.",
      reporter: "Operations PM",
      reviewStatus: "stable",
      tags: ["shipping", "post-purchase"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-auth-1",
      type: "SR",
      index: 1,
      domainIndex: 1,
      customPrefix: "AUTH",
      name: "Session-based authentication",
      priority: "R",
      content:
        "The system shall validate customer credentials and create an authenticated session token that expires automatically after inactivity.",
      acceptanceCriteria:
        "An authenticated customer can refresh the page and remain signed in until the session expires or they sign out.",
      reviewStatus: "approved",
      tags: ["auth", "session"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-cart-1",
      type: "SR",
      index: 2,
      domainIndex: 1,
      customPrefix: "CART",
      name: "Cart state management",
      priority: "R",
      content:
        "The system shall store cart line items, quantity, and subtotal, and shall update totals immediately after item changes.",
      acceptanceCriteria:
        "Removing the last line item resets the subtotal to zero and leaves the cart in an empty state.",
      reviewStatus: "approved",
      tags: ["cart", "pricing"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-pay-1",
      type: "SR",
      index: 3,
      domainIndex: 1,
      customPrefix: "PAY",
      name: "Payment authorization handling",
      priority: "R",
      content:
        "The system shall submit checkout payment requests once, persist the payment result, and block duplicate order creation on retries.",
      acceptanceCriteria:
        "A failed authorization keeps the cart open and shows a retryable error without creating an order record.",
      reviewStatus: "approved",
      tags: ["payment", "reliability"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-ship-1",
      type: "SR",
      index: 4,
      domainIndex: 1,
      customPrefix: "SHIP",
      name: "Order shipment status lookup",
      priority: "R",
      content:
        "The system shall expose the latest shipment status, carrier name, and most recent tracking timestamp for each completed order.",
      acceptanceCriteria:
        "Customers can see a simple status sequence such as paid, packed, shipped, and delivered without leaving the order page.",
      reviewStatus: "approved",
      tags: ["shipping", "tracking"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-auth-1",
      type: "FEATURE",
      index: 1,
      domainIndex: 1,
      customPrefix: "AUTH",
      name: "Login API endpoint",
      content:
        "API endpoint that validates email and password, returns a session token, and rejects invalid credentials with a typed error response.",
      owner: "Identity Team",
      verificationStatus: "passed",
      reviewStatus: "approved",
      tags: ["backend", "auth"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-cart-1",
      type: "FEATURE",
      index: 2,
      domainIndex: 1,
      customPrefix: "CART",
      name: "Cart summary service",
      content:
        "Service module that recalculates quantity and subtotal whenever shoppers add, remove, or update a line item.",
      owner: "Storefront Team",
      verificationStatus: "passed",
      reviewStatus: "approved",
      tags: ["frontend", "cart"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-pay-1",
      type: "FEATURE",
      index: 3,
      domainIndex: 1,
      customPrefix: "PAY",
      name: "Payment callback processor",
      content:
        "Checkout workflow step that stores gateway responses, marks the order as paid on success, and keeps the cart recoverable on failure.",
      owner: "Payments Team",
      verificationStatus: "pending",
      reviewStatus: "approved",
      tags: ["backend", "payment"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-ship-1",
      type: "FEATURE",
      index: 4,
      domainIndex: 1,
      customPrefix: "SHIP",
      name: "Delivery tracking panel",
      content:
        "Order detail panel that reads shipment status and renders the latest carrier update in a compact timeline.",
      owner: "Post-Purchase Team",
      verificationStatus: "pending",
      reviewStatus: "approved",
      tags: ["frontend", "shipping"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
  ],
  links: sharedLinks,
};

export const demoProjectDataKo: ProjectData = {
  project: {
    id: "project-demo-commerce-order-flow-ko",
    name: "커머스 주문 흐름 데모",
    version: "1.2.0",
    updatedAt: DEMO_UPDATED_AT,
  },
  items: [
    {
      id: "ur-auth-1",
      type: "UR",
      index: 1,
      domainIndex: 1,
      customPrefix: "AUTH",
      name: "회원 로그인",
      content:
        "기존 고객은 저장된 프로필과 주문 기능을 사용하기 전에 이메일과 비밀번호로 로그인할 수 있어야 한다.",
      reporter: "성장 PM",
      reviewStatus: "stable",
      tags: ["account", "mvp"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-cart-1",
      type: "UR",
      index: 2,
      domainIndex: 1,
      customPrefix: "CART",
      name: "장바구니 담기",
      content:
        "고객은 하나 이상의 상품을 장바구니에 담고, 수량을 조정하고, 결제 전에 최신 합계를 바로 확인할 수 있어야 한다.",
      reporter: "커머스 PM",
      reviewStatus: "stable",
      tags: ["cart", "mvp"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-pay-1",
      type: "UR",
      index: 3,
      domainIndex: 1,
      customPrefix: "PAY",
      name: "결제 완료",
      content:
        "고객은 현재 장바구니에 대해 결제를 제출하고, 중복 청구 없이 성공 또는 실패 결과를 명확히 확인할 수 있어야 한다.",
      reporter: "결제 PM",
      reviewStatus: "stable",
      tags: ["payment", "checkout"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ur-ship-1",
      type: "UR",
      index: 4,
      domainIndex: 1,
      customPrefix: "SHIP",
      name: "배송 상태 조회",
      content:
        "주문 이후 고객은 현재 배송 상태와 최신 배송 업데이트를 한 곳에서 확인할 수 있어야 한다.",
      reporter: "운영 PM",
      reviewStatus: "stable",
      tags: ["shipping", "post-purchase"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-auth-1",
      type: "SR",
      index: 1,
      domainIndex: 1,
      customPrefix: "AUTH",
      name: "세션 기반 인증",
      priority: "R",
      content:
        "시스템은 고객 자격 증명을 검증하고, 비활성 시간이 지나면 자동 만료되는 인증 세션 토큰을 발급해야 한다.",
      acceptanceCriteria:
        "인증된 고객은 세션 만료 또는 로그아웃 전까지 페이지를 새로고침해도 로그인 상태를 유지해야 한다.",
      reviewStatus: "approved",
      tags: ["auth", "session"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-cart-1",
      type: "SR",
      index: 2,
      domainIndex: 1,
      customPrefix: "CART",
      name: "장바구니 상태 관리",
      priority: "R",
      content:
        "시스템은 장바구니 항목, 수량, 합계를 저장하고, 항목 변경 직후 합계를 즉시 갱신해야 한다.",
      acceptanceCriteria:
        "마지막 항목이 제거되면 합계는 0이 되고 장바구니는 빈 상태로 남아야 한다.",
      reviewStatus: "approved",
      tags: ["cart", "pricing"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-pay-1",
      type: "SR",
      index: 3,
      domainIndex: 1,
      customPrefix: "PAY",
      name: "결제 승인 처리",
      priority: "R",
      content:
        "시스템은 결제 요청을 한 번만 제출하고, 결제 결과를 저장하며, 재시도 시 중복 주문 생성을 막아야 한다.",
      acceptanceCriteria:
        "승인 실패 시 주문 레코드는 생성되지 않고, 장바구니는 유지되며 재시도 가능한 오류를 보여줘야 한다.",
      reviewStatus: "approved",
      tags: ["payment", "reliability"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "sr-ship-1",
      type: "SR",
      index: 4,
      domainIndex: 1,
      customPrefix: "SHIP",
      name: "주문 배송 상태 조회",
      priority: "R",
      content:
        "시스템은 완료된 주문마다 최신 배송 상태, 택배사 이름, 마지막 추적 시각을 제공해야 한다.",
      acceptanceCriteria:
        "고객은 주문 화면에서 paid, packed, shipped, delivered 같은 단순 상태 흐름을 확인할 수 있어야 한다.",
      reviewStatus: "approved",
      tags: ["shipping", "tracking"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-auth-1",
      type: "FEATURE",
      index: 1,
      domainIndex: 1,
      customPrefix: "AUTH",
      name: "로그인 API 엔드포인트",
      content:
        "이메일과 비밀번호를 검증하고 세션 토큰을 반환하며, 잘못된 자격 증명에는 타입화된 오류 응답을 주는 API 엔드포인트.",
      owner: "인증 팀",
      verificationStatus: "passed",
      reviewStatus: "approved",
      tags: ["backend", "auth"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-cart-1",
      type: "FEATURE",
      index: 2,
      domainIndex: 1,
      customPrefix: "CART",
      name: "장바구니 합계 서비스",
      content:
        "고객이 항목을 추가, 제거, 수정할 때마다 수량과 합계를 다시 계산하는 서비스 모듈.",
      owner: "스토어프론트 팀",
      verificationStatus: "passed",
      reviewStatus: "approved",
      tags: ["frontend", "cart"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-pay-1",
      type: "FEATURE",
      index: 3,
      domainIndex: 1,
      customPrefix: "PAY",
      name: "결제 콜백 처리기",
      content:
        "결제 게이트웨이 응답을 저장하고, 성공 시 주문을 paid로 표시하며, 실패 시 장바구니를 복구 가능한 상태로 남기는 체크아웃 단계.",
      owner: "결제 팀",
      verificationStatus: "pending",
      reviewStatus: "approved",
      tags: ["backend", "payment"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
    {
      id: "ft-ship-1",
      type: "FEATURE",
      index: 4,
      domainIndex: 1,
      customPrefix: "SHIP",
      name: "배송 추적 패널",
      content:
        "배송 상태를 읽어 최신 택배사 업데이트를 간단한 타임라인으로 보여주는 주문 상세 패널.",
      owner: "구매후경험 팀",
      verificationStatus: "pending",
      reviewStatus: "approved",
      tags: ["frontend", "shipping"],
      createdAt: DEMO_UPDATED_AT,
      updatedAt: DEMO_UPDATED_AT,
    },
  ],
  links: sharedLinks,
};

export const demoProjectDataByLanguage: Record<DemoLanguage, ProjectData> = {
  en: demoProjectDataEn,
  ko: demoProjectDataKo,
};
